service:
  name: fight-server

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2
  stage: dev

functions:
  app:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get
